name: belcka
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.1+28

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  flutter_svg: ^2.2.3
  get_storage: ^2.1.1
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.1
  dio: ^5.9.1
  form_field_validator: ^1.1.0
  modal_progress_hud_nsn: ^0.5.1
  device_info_plus: ^11.5.0
  qr_code_scanner_plus: ^2.1.1
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.2
  video_player: ^2.11.0
  chewie: ^1.13.0
  path: ^1.9.0
  path_provider: ^2.1.3
  intl: ^0.20.2
  flutter_cache_manager: ^3.3.2
  permission_handler: ^11.4.0
  sms_autofill: ^2.4.0
  change_app_package_name: ^1.5.0
  photo_view: ^0.15.0
  flutter_html: ^3.0.0-beta.2
  image_cropper: ^11.0.0
  json_serializable: ^6.13.0
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  google_maps_flutter: ^2.14.2
  flutter_reorderable_grid_view: ^5.5.3
  webview_flutter: ^4.13.1
  webview_flutter_wkwebview: ^3.23.6
  syncfusion_flutter_datepicker: ^29.2.11
  keyboard_actions: ^4.2.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  flutter_local_notifications: ^20.1.0
  url_launcher: ^6.3.2
  http: ^1.6.0
  open_filex: ^4.7.0
  syncfusion_flutter_pdfviewer: ^29.2.11
  android_intent_plus: ^5.3.1
  audioplayers: ^6.1.0
  percent_indicator: ^4.2.3
#  cupertino_native: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/icon_ios.png"
  image_path_android: "assets/icon/icon_fg.png"
  adaptive_icon_background: "assets/icon/icon_bg.png"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/country_flag/
    - assets/user_permission_icons/